apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
  namespace: openshift-operators
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: argocd-operator
  source: argocd-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: argocd-operator.v0.9.2
